spring.application.name=SpringBootOauth2

spring.security.oauth2.client.registration.google.client-id=your_actual_client_id
spring.security.oauth2.client.registration.google.client-secret=your_actual_secret_key
